name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/**.md'
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: .

permissions:
  contents: read

jobs:
  build:
    name: Build for ${{matrix.BUILD_CONFIGURATION}}
    runs-on: windows-latest
    strategy:
      matrix:
        BUILD_CONFIGURATION:
          - Debug
          - Release
          - Dist
      
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Generate Project Files
      run: "./GenerateProjectFiles.bat"
      
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /t:Clean
